baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "http://www.mustafabuda.com" # the base hostname & protocol for your site.
title: "Mustafa Buda"

paginate: 10 #articles per page
paginate_path: /blog/page:num #makes pagination working

parse_block_html: true

#contacts
git: "https://github.com/mbuda03"  #your github url here.
stackoverflow: "" #Add your stackoverflow url here.
twitter: "https://twitter.com/mbuda03"  #Add your twitter url here.

#disqus comment
disqus:
    shortname: "" #your disqus comment short name

#google analytics
google:
    tracking-id: "UA-24380181-1" #your tracking id here

gems:
  - jekyll-sitemap
  - jekyll-paginate

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

  
# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"

permalink: /posts/:title

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
