baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "http://www.mustafabuda.com" # the base hostname & protocol for your site.
title: "Mustafa Buda"


# A description of your site for social meta tag, search engines, and feed.xml
description: "Sometimes I write code"

# Tagline near the site title
tagline: "Sometimes I write code"



# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Style Guides
  url: /style-guide/
- text: Archives
  url: /tags/



# Author information - author info at the bottom of the post
author_name: "Mustafa Buda"
author_bio: "I am a Full-Stack Developer, Security Analyst, Photographer and a Cyclist"
author_url:  "http://www.mustafabuda.com"
author_location: "Nicosia, Cyprus"
author_image: /images/authorimage.png


# Sidebar Add banner
banner_url: "http://justgoodthemes.com"
banner_image: images/banner.jpg


# Sidebar newsletter widget - add your form action url for MailChimp signup form here
mailchimp_url: "//mustafabuda.us14.list-manage.com/subscribe/post?u=8c143194c2a2a5c205d7587d6&amp;id=1abecbf73d"

# Social links in the site footer
twitter_username: "mbuda03"
facebook_username: "mustafa.buda"
googleplus_username: "+MustafaBuda"
github_username: "MBuda03"
#codepen_username: "username"
#dribbble_uername: "username"
#medium_username: "@username"
instagram_username: "musdyy"
#pinterest_username: "username"
#linkedin_username: "username"


paginate: 5 #articles per page
paginate_path: /blog/page:num #makes pagination working
gems: [jekyll-paginate]

parse_block_html: true

sass:
  sass_dir: _sass

#google analytics
google:
    tracking-id: "UA-24380181-1" #your tracking id here

gems:
  - jekyll-sitemap
  - jekyll-paginate

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
